export const USERS = [
  { role: "fa", userName: "fa", token: "xxx.yyy.zzz" },
  { role: "lean", userName: "lean", token: "xxx.yyy.zzz" },
  { role: "cutting", userName: "cutting", token: "xxx.yyy.zzz" },
  { role: "mpc", userName: "mpc", token: "xxx.yyy.zzz" },
  { role: "root", userName: "root", token: "xxx.yyy.zzz" },
];

export const BESTCREW = [
  {
    month: "2024-01",
    data: [
      {
        crew: "k05C",
        efficiency: { act: 94, target: 84 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 100, target: 100 },
      },
      {
        crew: "k01A",
        efficiency: { act: 85, target: 75 },
        abs: { act: "3%", target: "5%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: 95, target: 98 },
      },
      {
        crew: "k01B",
        efficiency: { act: 88, target: 78 },
        abs: { act: "2%", target: "4%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 105, target: 95 },
      },
      {
        crew: "k04C",
        efficiency: { act: 90, target: 80 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 102, target: 99 },
      },
      {
        crew: "k05B",
        efficiency: { act: 85, target: 80 },
        abs: { act: "4%", target: "5%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 98, target: 97 },
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        crew: "k03C",
        efficiency: { act: 90, target: 80 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 100, target: 100 },
      },
      {
        crew: "k02A",
        efficiency: { act: 87, target: 77 },
        abs: { act: "3%", target: "5%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: 96, target: 100 },
      },
      {
        crew: "k04B",
        efficiency: { act: 88, target: 78 },
        abs: { act: "2%", target: "4%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 97, target: 98 },
      },
      {
        crew: "k02B",
        efficiency: { act: 89, target: 79 },
        abs: { act: "2%", target: "4%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: 101, target: 99 },
      },
      {
        crew: "k02C",
        efficiency: { act: 91, target: 81 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 99, target: 102 },
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        crew: "k02C",
        efficiency: { act: 91, target: 81 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 100, target: 100 },
      },
      {
        crew: "k03A",
        efficiency: { act: 86, target: 76 },
        abs: { act: "2%", target: "5%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: 95, target: 96 },
      },
      {
        crew: "k03B",
        efficiency: { act: 88, target: 78 },
        abs: { act: "2%", target: "4%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 98, target: 97 },
      },
      {
        crew: "k03C",
        efficiency: { act: 90, target: 80 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 99, target: 98 },
      },
      {
        crew: "k05A",
        efficiency: { act: 90, target: 80 },
        abs: { act: "2%", target: "5%" },
        cc: { act: 3, target: 5 },
        dailyKaizen: { act: 104, target: 102 },
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        crew: "k05A",
        efficiency: { act: 90, target: 80 },
        abs: { act: "2%", target: "5%" },
        cc: { act: 3, target: 5 },
        dailyKaizen: { act: 102, target: 104 },
      },
      {
        crew: "R04A",
        efficiency: { act: 89, target: 79 },
        abs: { act: "3%", target: "5%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: 98, target: 99 },
      },
      {
        crew: "X04B",
        efficiency: { act: 92, target: 82 },
        abs: { act: "2%", target: "4%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 101, target: 102 },
      },
      {
        crew: "k04C",
        efficiency: { act: 94, target: 84 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 100, target: 100 },
      },
      {
        crew: "k03C",
        efficiency: { act: 90, target: 80 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 99, target: 101 },
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        crew: "k03A",
        efficiency: { act: 86, target: 76 },
        abs: { act: "2%", target: "5%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: 97, target: 96 },
      },
      {
        crew: "k05A",
        efficiency: { act: 90, target: 80 },
        abs: { act: "2%", target: "5%" },
        cc: { act: 3, target: 5 },
        dailyKaizen: { act: 98, target: 100 },
      },
      {
        crew: "R05B",
        efficiency: { act: 85, target: 80 },
        abs: { act: "4%", target: "5%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 101, target: 104 },
      },
      {
        crew: "B01C",
        efficiency: { act: 88, target: 78 },
        abs: { act: "3%", target: "4%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 100, target: 102 },
      },
      {
        crew: "X03C",
        efficiency: { act: 90, target: 80 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: 99, target: 101 },
      },
    ],
  },
];

export const BESTCUTTING = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 6862,
        pmh: "80%",
        setupTime: "70%",
        downTime: "100%",
        dailyKaizen: { act: 59, target: 76 },
      },
      {
        matricule: 1234,
        pmh: "85%",
        setupTime: "75%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
      {
        matricule: 5678,
        pmh: "90%",
        setupTime: "80%",
        downTime: "100%",
        dailyKaizen: { act: 65, target: 82 },
      },
      {
        matricule: 4321,
        pmh: "82%",
        setupTime: "72%",
        downTime: "100%",
        dailyKaizen: { act: 61, target: 78 },
      },
      {
        matricule: 8765,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        dailyKaizen: { act: 63, target: 80 },
      },
      {
        matricule: 3456,
        pmh: "81%",
        setupTime: "71%",
        downTime: "100%",
        dailyKaizen: { act: 60, target: 77 },
      },
      {
        matricule: 7890,
        pmh: "87%",
        setupTime: "77%",
        downTime: "100%",
        dailyKaizen: { act: 64, target: 81 },
      },
      {
        matricule: 4567,
        pmh: "83%",
        setupTime: "73%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
      {
        matricule: 8901,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        dailyKaizen: { act: 63, target: 80 },
      },
      {
        matricule: 5670,
        pmh: "89%",
        setupTime: "79%",
        downTime: "100%",
        dailyKaizen: { act: 66, target: 83 },
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 2345,
        pmh: "82%",
        setupTime: "72%",
        downTime: "100%",
        dailyKaizen: { act: 61, target: 78 },
      },
      {
        matricule: 6789,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        dailyKaizen: { act: 64, target: 81 },
      },
      {
        matricule: 3452,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
      {
        matricule: 7893,
        pmh: "81%",
        setupTime: "71%",
        downTime: "100%",
        dailyKaizen: { act: 60, target: 77 },
      },
      {
        matricule: 4568,
        pmh: "87%",
        setupTime: "77%",
        downTime: "100%",
        dailyKaizen: { act: 65, target: 82 },
      },
      {
        matricule: 8902,
        pmh: "83%",
        setupTime: "73%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
      {
        matricule: 5671,
        pmh: "89%",
        setupTime: "79%",
        downTime: "100%",
        dailyKaizen: { act: 66, target: 83 },
      },
      {
        matricule: 6780,
        pmh: "85%",
        setupTime: "75%",
        downTime: "100%",
        dailyKaizen: { act: 63, target: 80 },
      },
      {
        matricule: 7891,
        pmh: "88%",
        setupTime: "78%",
        downTime: "100%",
        dailyKaizen: { act: 65, target: 82 },
      },
      {
        matricule: 8903,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        dailyKaizen: { act: 64, target: 81 },
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 3456,
        pmh: "83%",
        setupTime: "73%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
      {
        matricule: 7890,
        pmh: "87%",
        setupTime: "77%",
        downTime: "100%",
        dailyKaizen: { act: 65, target: 82 },
      },
      {
        matricule: 4567,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
      {
        matricule: 8901,
        pmh: "85%",
        setupTime: "75%",
        downTime: "100%",
        dailyKaizen: { act: 63, target: 80 },
      },
      {
        matricule: 5670,
        pmh: "81%",
        setupTime: "71%",
        downTime: "100%",
        dailyKaizen: { act: 60, target: 77 },
      },
      {
        matricule: 6780,
        pmh: "89%",
        setupTime: "79%",
        downTime: "100%",
        dailyKaizen: { act: 66, target: 83 },
      },
      {
        matricule: 7891,
        pmh: "88%",
        setupTime: "78%",
        downTime: "100%",
        dailyKaizen: { act: 65, target: 82 },
      },
      {
        matricule: 8902,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        dailyKaizen: { act: 64, target: 81 },
      },
      {
        matricule: 5671,
        pmh: "82%",
        setupTime: "72%",
        downTime: "100%",
        dailyKaizen: { act: 61, target: 78 },
      },
      {
        matricule: 6781,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 4567,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        dailyKaizen: { act: 64, target: 81 },
      },
      {
        matricule: 8901,
        pmh: "82%",
        setupTime: "72%",
        downTime: "100%",
        dailyKaizen: { act: 61, target: 78 },
      },
      {
        matricule: 5670,
        pmh: "83%",
        setupTime: "73%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
      {
        matricule: 6780,
        pmh: "89%",
        setupTime: "79%",
        downTime: "100%",
        dailyKaizen: { act: 66, target: 83 },
      },
      {
        matricule: 7891,
        pmh: "88%",
        setupTime: "78%",
        downTime: "100%",
        dailyKaizen: { act: 65, target: 82 },
      },
      {
        matricule: 8902,
        pmh: "85%",
        setupTime: "75%",
        downTime: "100%",
        dailyKaizen: { act: 63, target: 80 },
      },
      {
        matricule: 5671,
        pmh: "87%",
        setupTime: "77%",
        downTime: "100%",
        dailyKaizen: { act: 65, target: 82 },
      },
      {
        matricule: 6781,
        pmh: "81%",
        setupTime: "71%",
        downTime: "100%",
        dailyKaizen: { act: 60, target: 77 },
      },
      {
        matricule: 7892,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
      {
        matricule: 8903,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        dailyKaizen: { act: 64, target: 81 },
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 5670,
        pmh: "80%",
        setupTime: "70%",
        downTime: "100%",
        dailyKaizen: { act: 59, target: 76 },
      },
      {
        matricule: 6780,
        pmh: "85%",
        setupTime: "75%",
        downTime: "100%",
        dailyKaizen: { act: 63, target: 80 },
      },
      {
        matricule: 7890,
        pmh: "90%",
        setupTime: "80%",
        downTime: "100%",
        dailyKaizen: { act: 66, target: 83 },
      },
      {
        matricule: 8900,
        pmh: "82%",
        setupTime: "72%",
        downTime: "100%",
        dailyKaizen: { act: 61, target: 78 },
      },
      {
        matricule: 1234,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
      {
        matricule: 2345,
        pmh: "81%",
        setupTime: "71%",
        downTime: "100%",
        dailyKaizen: { act: 60, target: 77 },
      },
      {
        matricule: 3456,
        pmh: "87%",
        setupTime: "77%",
        downTime: "100%",
        dailyKaizen: { act: 65, target: 82 },
      },
      {
        matricule: 4567,
        pmh: "83%",
        setupTime: "73%",
        downTime: "100%",
        dailyKaizen: { act: 62, target: 79 },
      },
      {
        matricule: 5678,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        dailyKaizen: { act: 64, target: 81 },
      },
      {
        matricule: 6789,
        pmh: "89%",
        setupTime: "79%",
        downTime: "100%",
        dailyKaizen: { act: 66, target: 83 },
      },
    ],
  },
];


export const BESTLPOP = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 6268,
        pmh: "86%",
      },
      {
        matricule: 1234,
        pmh: "85%",
      },
      {
        matricule: 5678,
        pmh: "90%",
      },
      {
        matricule: 4321,
        pmh: "82%",
      },
      {
        matricule: 8765,
        pmh: "84%",
      },
      {
        matricule: 3456,
        pmh: "81%",
      },
      {
        matricule: 7890,
        pmh: "87%",
      },
      {
        matricule: 4567,
        pmh: "83%",
      },
      {
        matricule: 8901,
        pmh: "86%",
      },
      {
        matricule: 5670,
        pmh: "89%",
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 2345,
        pmh: "82%",
      },
      {
        matricule: 6789,
        pmh: "86%",
      },
      {
        matricule: 3452,
        pmh: "84%",
      },
      {
        matricule: 7893,
        pmh: "81%",
      },
      {
        matricule: 4568,
        pmh: "87%",
      },
      {
        matricule: 8902,
        pmh: "83%",
      },
      {
        matricule: 5671,
        pmh: "89%",
      },
      {
        matricule: 6780,
        pmh: "85%",
      },
      {
        matricule: 7891,
        pmh: "88%",
      },
      {
        matricule: 8903,
        pmh: "86%",
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 3456,
        pmh: "83%",
      },
      {
        matricule: 7890,
        pmh: "87%",
      },
      {
        matricule: 4567,
        pmh: "84%",
      },
      {
        matricule: 8901,
        pmh: "85%",
      },
      {
        matricule: 5670,
        pmh: "81%",
      },
      {
        matricule: 6780,
        pmh: "89%",
      },
      {
        matricule: 7891,
        pmh: "88%",
      },
      {
        matricule: 8902,
        pmh: "86%",
      },
      {
        matricule: 5671,
        pmh: "82%",
      },
      {
        matricule: 6781,
        pmh: "84%",
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 4567,
        pmh: "86%",
      },
      {
        matricule: 8901,
        pmh: "82%",
      },
      {
        matricule: 5670,
        pmh: "83%",
      },
      {
        matricule: 6780,
        pmh: "89%",
      },
      {
        matricule: 7891,
        pmh: "88%",
      },
      {
        matricule: 8902,
        pmh: "85%",
      },
      {
        matricule: 5671,
        pmh: "87%",
      },
      {
        matricule: 6781,
        pmh: "81%",
      },
      {
        matricule: 7892,
        pmh: "84%",
      },
      {
        matricule: 8903,
        pmh: "86%",
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 5670,
        pmh: "80%",
      },
      {
        matricule: 6780,
        pmh: "85%",
      },
      {
        matricule: 7890,
        pmh: "90%",
      },
      {
        matricule: 8900,
        pmh: "82%",
      },
      {
        matricule: 1234,
        pmh: "84%",
      },
      {
        matricule: 2345,
        pmh: "81%",
      },
      {
        matricule: 3456,
        pmh: "87%",
      },
      {
        matricule: 4567,
        pmh: "83%",
      },
      {
        matricule: 5678,
        pmh: "86%",
      },
      {
        matricule: 6789,
        pmh: "89%",
      },
    ],
  },
];

export const QUALITYHERO = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 2635,
        detection: 4,
        occurrence: 2,
        security: 3,
        rating: 3,
      },
      {
        matricule: 1234,
        detection: 3,
        occurrence: 1,
        security: 4,
        rating: 4,
      },
      {
        matricule: 5678,
        detection: 2,
        occurrence: 4,
        security: 5,
        rating: 2,
      },
      {
        matricule: 4321,
        detection: 5,
        occurrence: 3,
        security: 1,
        rating: 5,
      },
      {
        matricule: 8765,
        detection: 1,
        occurrence: 5,
        security: 2,
        rating: 1,
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 3456,
        detection: 3,
        occurrence: 2,
        security: 5,
        rating: 3,
      },
      {
        matricule: 7890,
        detection: 4,
        occurrence: 1,
        security: 3,
        rating: 4,
      },
      {
        matricule: 4567,
        detection: 2,
        occurrence: 3,
        security: 4,
        rating: 2,
      },
      {
        matricule: 8901,
        detection: 5,
        occurrence: 4,
        security: 1,
        rating: 5,
      },
      {
        matricule: 5670,
        detection: 1,
        occurrence: 5,
        security: 2,
        rating: 1,
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 6780,
        detection: 2,
        occurrence: 1,
        security: 4,
        rating: 2,
      },
      {
        matricule: 7891,
        detection: 3,
        occurrence: 5,
        security: 2,
        rating: 3,
      },
      {
        matricule: 8902,
        detection: 4,
        occurrence: 2,
        security: 3,
        rating: 4,
      },
      {
        matricule: 5671,
        detection: 1,
        occurrence: 4,
        security: 5,
        rating: 1,
      },
      {
        matricule: 6781,
        detection: 5,
        occurrence: 3,
        security: 1,
        rating: 5,
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 7892,
        detection: 4,
        occurrence: 5,
        security: 2,
        rating: 4,
      },
      {
        matricule: 8903,
        detection: 3,
        occurrence: 1,
        security: 4,
        rating: 3,
      },
      {
        matricule: 5672,
        detection: 2,
        occurrence: 3,
        security: 5,
        rating: 2,
      },
      {
        matricule: 6782,
        detection: 1,
        occurrence: 4,
        security: 3,
        rating: 1,
      },
      {
        matricule: 7893,
        detection: 5,
        occurrence: 2,
        security: 1,
        rating: 5,
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 8904,
        detection: 3,
        occurrence: 4,
        security: 2,
        rating: 3,
      },
      {
        matricule: 5673,
        detection: 4,
        occurrence: 1,
        security: 5,
        rating: 4,
      },
      {
        matricule: 6783,
        detection: 2,
        occurrence: 5,
        security: 3,
        rating: 2,
      },
      {
        matricule: 7894,
        detection: 5,
        occurrence: 2,
        security: 1,
        rating: 5,
      },
      {
        matricule: 8905,
        detection: 1,
        occurrence: 3,
        security: 4,
        rating: 1,
      },
    ],
  },
];

export const SAFETYHERO = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 3456,
        detection: 2,
        occurrence: 3,
        security: 4,
        rating: 3,
      },
      {
        matricule: 7890,
        detection: 4,
        occurrence: 1,
        security: 5,
        rating: 4,
      },
      {
        matricule: 1235,
        detection: 3,
        occurrence: 2,
        security: 1,
        rating: 2,
      },
      {
        matricule: 6789,
        detection: 5,
        occurrence: 4,
        security: 3,
        rating: 5,
      },
      {
        matricule: 4568,
        detection: 1,
        occurrence: 5,
        security: 2,
        rating: 1,
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 2345,
        detection: 4,
        occurrence: 1,
        security: 3,
        rating: 4,
      },
      {
        matricule: 6780,
        detection: 3,
        occurrence: 5,
        security: 2,
        rating: 3,
      },
      {
        matricule: 5671,
        detection: 1,
        occurrence: 4,
        security: 5,
        rating: 1,
      },
      {
        matricule: 8902,
        detection: 2,
        occurrence: 3,
        security: 1,
        rating: 2,
      },
      {
        matricule: 7891,
        detection: 5,
        occurrence: 2,
        security: 4,
        rating: 5,
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 5670,
        detection: 3,
        occurrence: 4,
        security: 2,
        rating: 3,
      },
      {
        matricule: 6781,
        detection: 4,
        occurrence: 1,
        security: 5,
        rating: 4,
      },
      {
        matricule: 8903,
        detection: 2,
        occurrence: 5,
        security: 3,
        rating: 2,
      },
      {
        matricule: 7892,
        detection: 1,
        occurrence: 3,
        security: 4,
        rating: 1,
      },
      {
        matricule: 5672,
        detection: 5,
        occurrence: 2,
        security: 1,
        rating: 5,
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 6782,
        detection: 3,
        occurrence: 4,
        security: 5,
        rating: 3,
      },
      {
        matricule: 8904,
        detection: 1,
        occurrence: 5,
        security: 2,
        rating: 1,
      },
      {
        matricule: 7893,
        detection: 4,
        occurrence: 2,
        security: 1,
        rating: 4,
      },
      {
        matricule: 5673,
        detection: 5,
        occurrence: 3,
        security: 4,
        rating: 5,
      },
      {
        matricule: 6783,
        detection: 2,
        occurrence: 1,
        security: 3,
        rating: 2,
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 8905,
        detection: 5,
        occurrence: 4,
        security: 3,
        rating: 5,
      },
      {
        matricule: 7894,
        detection: 1,
        occurrence: 3,
        security: 5,
        rating: 1,
      },
      {
        matricule: 5674,
        detection: 4,
        occurrence: 2,
        security: 1,
        rating: 4,
      },
      {
        matricule: 6784,
        detection: 2,
        occurrence: 5,
        security: 4,
        rating: 2,
      },
      {
        matricule: 8906,
        detection: 3,
        occurrence: 1,
        security: 2,
        rating: 3,
      },
    ],
  },
];

export const LEANHERO = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 3456,
        detection: 2,
        occurrence: 3,
        security: "yes",
        rating: 3,
      },
      {
        matricule: 7890,
        detection: 4,
        occurrence: 1,
        security: "yes",
        rating: 4,
      },
      {
        matricule: 1235,
        detection: 3,
        occurrence: 2,
        security: "no",
        rating: 2,
      },
      {
        matricule: 6789,
        detection: 5,
        occurrence: 4,
        security: "yes",
        rating: 5,
      },
      {
        matricule: 4568,
        detection: 1,
        occurrence: 5,
        security: "no",
        rating: 1,
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 2345,
        detection: 4,
        occurrence: 1,
        security: "yes",
        rating: 4,
      },
      {
        matricule: 6780,
        detection: 3,
        occurrence: 5,
        security: "no",
        rating: 3,
      },
      {
        matricule: 5671,
        detection: 1,
        occurrence: 4,
        security: "yes",
        rating: 1,
      },
      {
        matricule: 8902,
        detection: 2,
        occurrence: 3,
        security: "no",
        rating: 2,
      },
      {
        matricule: 7891,
        detection: 5,
        occurrence: 2,
        security: "yes",
        rating: 5,
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 5670,
        detection: 3,
        occurrence: 4,
        security: "no",
        rating: 3,
      },
      {
        matricule: 6781,
        detection: 4,
        occurrence: 1,
        security: "yes",
        rating: 4,
      },
      {
        matricule: 8903,
        detection: 2,
        occurrence: 5,
        security: "yes",
        rating: 2,
      },
      {
        matricule: 7892,
        detection: 1,
        occurrence: 3,
        security: "yes",
        rating: 1,
      },
      {
        matricule: 5672,
        detection: 5,
        occurrence: 2,
        security: "no",
        rating: 5,
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 6782,
        detection: 3,
        occurrence: 4,
        security: "yes",
        rating: 3,
      },
      {
        matricule: 8904,
        detection: 1,
        occurrence: 5,
        security: "no",
        rating: 1,
      },
      {
        matricule: 7893,
        detection: 4,
        occurrence: 2,
        security: "no",
        rating: 4,
      },
      {
        matricule: 5673,
        detection: 5,
        occurrence: 3,
        security: "yes",
        rating: 5,
      },
      {
        matricule: 6783,
        detection: 2,
        occurrence: 1,
        security: "yes",
        rating: 2,
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 8905,
        detection: 5,
        occurrence: 4,
        security: "yes",
        rating: 5,
      },
      {
        matricule: 7894,
        detection: 1,
        occurrence: 3,
        security: "yes",
        rating: 1,
      },
      {
        matricule: 5674,
        detection: 4,
        occurrence: 2,
        security: "no",
        rating: 4,
      },
      {
        matricule: 6784,
        detection: 2,
        occurrence: 5,
        security: "yes",
        rating: 2,
      },
      {
        matricule: 8906,
        detection: 3,
        occurrence: 1,
        security: "no",
        rating: 3,
      },
    ],
  },
];

export const PROJECTCI = [
  {
    month: "2024-01",
    data: [
      {
        projectName: "Customer Service",
        leader: "Wafaa",
        teamMembers: ["Ibrahim", "Sara"],
        saving: 490,
        approach: "Improving customer interaction methods",
        rating: 3,
      },
      {
        projectName: "Automation",
        leader: "Fatima",
        teamMembers: ["Khalid", "Sami"],
        saving: 500,
        approach: "Streamlining workflows with AI tools",
        rating: 4,
      },
      {
        projectName: "Optimization",
        leader: "Mehdi",
        teamMembers: ["Laila", "Nour"],
        saving: 600,
        approach: "Enhancing data analysis methods",
        rating: 2,
      },
      {
        projectName: "Digitization",
        leader: "Rachid",
        teamMembers: ["Yasmine", "Hamza"],
        saving: 450,
        approach: "Converting manual processes to digital",
        rating: 1,
      },
      {
        projectName: "Sustainability",
        leader: "Sara",
        teamMembers: ["Amine", "Sofia"],
        saving: 550,
        approach: "Implementing eco-friendly practices",
        rating: 5,
      },
      {
        projectName: "Innovation",
        leader: "Hassan",
        teamMembers: ["Omar", "Layla"],
        saving: 620,
        approach: "Developing new product features",
        rating: 3,
      },
      {
        projectName: "Expansion",
        leader: "Khadija",
        teamMembers: ["Mohammed", "Nada"],
        saving: 480,
        approach: "Exploring new market opportunities",
        rating: 4,
      },
      {
        projectName: "Integration",
        leader: "Youssef",
        teamMembers: ["Zineb", "Salma"],
        saving: 700,
        approach: "Combining systems for efficiency",
        rating: 5,
      },
      {
        projectName: "Training",
        leader: "Amina",
        teamMembers: ["Ali", "Nadia"],
        saving: 510,
        approach: "Enhancing skills through workshops",
        rating: 2,
      },
      {
        projectName: "Research",
        leader: "Karim",
        teamMembers: ["Mounir", "Rania"],
        saving: 530,
        approach: "Conducting in-depth market analysis",
        rating: 3,
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        projectName: "Security",
        leader: "Othman",
        teamMembers: ["Hiba", "Samir"],
        saving: 470,
        approach: "Implementing advanced security protocols",
        rating: 3,
      },
      {
        projectName: "Customer Service",
        leader: "Wafaa",
        teamMembers: ["Ibrahim", "Sara"],
        saving: 490,
        approach: "Improving customer interaction methods",
        rating: 4,
      },
      {
        projectName: "Compliance",
        leader: "Ismail",
        teamMembers: ["Farah", "Younes"],
        saving: 610,
        approach: "Ensuring adherence to regulations",
        rating: 1,
      },
      {
        projectName: "Collaboration",
        leader: "Samira",
        teamMembers: ["Meryem", "Yassine"],
        saving: 560,
        approach: "Enhancing team collaboration tools",
        rating: 4,
      },
      {
        projectName: "Sustainability",
        leader: "Sara",
        teamMembers: ["Amine", "Sofia"],
        saving: 550,
        approach: "Implementing eco-friendly practices",
        rating: 5,
      },
      {
        projectName: "Expansion",
        leader: "Khadija",
        teamMembers: ["Mohammed", "Nada"],
        saving: 480,
        approach: "Exploring new market opportunities",
        rating: 4,
      },
      {
        projectName: "Integration",
        leader: "Youssef",
        teamMembers: ["Zineb", "Salma"],
        saving: 700,
        approach: "Combining systems for efficiency",
        rating: 5,
      },
      {
        projectName: "Training",
        leader: "Amina",
        teamMembers: ["Ali", "Nadia"],
        saving: 510,
        approach: "Enhancing skills through workshops",
        rating: 2,
      },
      {
        projectName: "Research",
        leader: "Karim",
        teamMembers: ["Mounir", "Rania"],
        saving: 530,
        approach: "Conducting in-depth market analysis",
        rating: 3,
      },
      {
        projectName: "Innovation",
        leader: "Hassan",
        teamMembers: ["Omar", "Layla"],
        saving: 620,
        approach: "Developing new product features",
        rating: 4,
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        projectName: "Automation",
        leader: "Fatima",
        teamMembers: ["Khalid", "Sami"],
        saving: 500,
        approach: "Streamlining workflows with AI tools",
        rating: 4,
      },
      {
        projectName: "Optimization",
        leader: "Mehdi",
        teamMembers: ["Laila", "Nour"],
        saving: 600,
        approach: "Enhancing data analysis methods",
        rating: 2,
      },
      {
        projectName: "Digitization",
        leader: "Rachid",
        teamMembers: ["Yasmine", "Hamza"],
        saving: 450,
        approach: "Converting manual processes to digital",
        rating: 1,
      },
      {
        projectName: "Security",
        leader: "Othman",
        teamMembers: ["Hiba", "Samir"],
        saving: 470,
        approach: "Implementing advanced security protocols",
        rating: 3,
      },
      {
        projectName: "Customer Service",
        leader: "Wafaa",
        teamMembers: ["Ibrahim", "Sara"],
        saving: 490,
        approach: "Improving customer interaction methods",
        rating: 4,
      },
      {
        projectName: "Compliance",
        leader: "Ismail",
        teamMembers: ["Farah", "Younes"],
        saving: 610,
        approach: "Ensuring adherence to regulations",
        rating: 1,
      },
      {
        projectName: "Collaboration",
        leader: "Samira",
        teamMembers: ["Meryem", "Yassine"],
        saving: 560,
        approach: "Enhancing team collaboration tools",
        rating: 4,
      },
      {
        projectName: "Innovation",
        leader: "Hassan",
        teamMembers: ["Omar", "Layla"],
        saving: 620,
        approach: "Developing new product features",
        rating: 4,
      },
      {
        projectName: "Expansion",
        leader: "Khadija",
        teamMembers: ["Mohammed", "Nada"],
        saving: 480,
        approach: "Exploring new market opportunities",
        rating: 4,
      },
      {
        projectName: "Integration",
        leader: "Youssef",
        teamMembers: ["Zineb", "Salma"],
        saving: 700,
        approach: "Combining systems for efficiency",
        rating: 5,
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        projectName: "Training",
        leader: "Amina",
        teamMembers: ["Ali", "Nadia"],
        saving: 510,
        approach: "Enhancing skills through workshops",
        rating: 2,
      },
      {
        projectName: "Research",
        leader: "Karim",
        teamMembers: ["Mounir", "Rania"],
        saving: 530,
        approach: "Conducting in-depth market analysis",
        rating: 3,
      },
      {
        projectName: "Optimization",
        leader: "Mehdi",
        teamMembers: ["Laila", "Nour"],
        saving: 600,
        approach: "Enhancing data analysis methods",
        rating: 2,
      },
      {
        projectName: "Digitization",
        leader: "Rachid",
        teamMembers: ["Yasmine", "Hamza"],
        saving: 450,
        approach: "Converting manual processes to digital",
        rating: 1,
      },
      {
        projectName: "Sustainability",
        leader: "Sara",
        teamMembers: ["Amine", "Sofia"],
        saving: 550,
        approach: "Implementing eco-friendly practices",
        rating: 5,
      },
      {
        projectName: "Innovation",
        leader: "Hassan",
        teamMembers: ["Omar", "Layla"],
        saving: 620,
        approach: "Developing new product features",
        rating: 4,
      },
      {
        projectName: "Expansion",
        leader: "Khadija",
        teamMembers: ["Mohammed", "Nada"],
        saving: 480,
        approach: "Exploring new market opportunities",
        rating: 4,
      },
      {
        projectName: "Integration",
        leader: "Youssef",
        teamMembers: ["Zineb", "Salma"],
        saving: 700,
        approach: "Combining systems for efficiency",
        rating: 5,
      },
      {
        projectName: "Automation",
        leader: "Fatima",
        teamMembers: ["Khalid", "Sami"],
        saving: 500,
        approach: "Streamlining workflows with AI tools",
        rating: 4,
      },
      {
        projectName: "Collaboration",
        leader: "Samira",
        teamMembers: ["Meryem", "Yassine"],
        saving: 560,
        approach: "Enhancing team collaboration tools",
        rating: 4,
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        projectName: "Recognition",
        leader: "Ouassil",
        teamMembers: ["Anass", "Yazid"],
        saving: 400,
        approach:
          "Development of an app to facilitate and improve the process of the recognition ceremony in the company",
        rating: 3,
      },
      {
        projectName: "Compliance",
        leader: "Ismail",
        teamMembers: ["Farah", "Younes", "Yassine"],
        saving: 610,
        approach: "Ensuring adherence to regulations",
        rating: 1,
      },
      {
        projectName: "Collaboration",
        leader: "Samira",
        teamMembers: ["Meryem", "Yassine"],
        saving: 560,
        approach: "Enhancing team collaboration tools",
        rating: 4,
      },
      {
        projectName: "Training",
        leader: "Amina",
        teamMembers: ["Ali", "Nadia"],
        saving: 510,
        approach: "Enhancing skills through workshops",
        rating: 2,
      },
      {
        projectName: "Research",
        leader: "Karim",
        teamMembers: ["Mounir", "Rania"],
        saving: 530,
        approach: "Conducting in-depth market analysis",
        rating: 3,
      },
      {
        projectName: "Sustainability",
        leader: "Sara",
        teamMembers: ["Amine", "Sofia"],
        saving: 550,
        approach: "Implementing eco-friendly practices",
        rating: 5,
      },
      {
        projectName: "Optimization",
        leader: "Mehdi",
        teamMembers: ["Laila", "Nour"],
        saving: 600,
        approach: "Enhancing data analysis methods",
        rating: 2,
      },
      {
        projectName: "Digitalization",
        leader: "Rachid",
        teamMembers: ["Yasmine", "Hamza"],
        saving: 450,
        approach: "Converting manual processes to digital",
        rating: 1,
      },
      {
        projectName: "Innovation",
        leader: "Hassan",
        teamMembers: ["Omar", "Layla"],
        saving: 620,
        approach: "Developing new product features",
        rating: 4,
      },
      {
        projectName: "Expansion",
        leader: "Khadija",
        teamMembers: ["Mohammed", "Nada"],
        saving: 480,
        approach: "Exploring new market opportunities",
        rating: 4,
      },
    ],
  },
];

export const MPC = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 381,
        dciwmse: "60%",
        dciwmseTarget: "55%",
        workload: "70%",
        workloadTarget: "65%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 482,
        dciwmse: "58%",
        dciwmseTarget: "52%",
        workload: "68%",
        workloadTarget: "63%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 573,
        dciwmse: "62%",
        dciwmseTarget: "58%",
        workload: "72%",
        workloadTarget: "67%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 694,
        dciwmse: "59%",
        dciwmseTarget: "54%",
        workload: "69%",
        workloadTarget: "64%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 785,
        dciwmse: "61%",
        dciwmseTarget: "56%",
        workload: "71%",
        workloadTarget: "66%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 826,
        dciwmse: "63%",
        dciwmseTarget: "59%",
        workload: "73%",
        workloadTarget: "68%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 947,
        dciwmse: "57%",
        dciwmseTarget: "51%",
        workload: "67%",
        workloadTarget: "62%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 108,
        dciwmse: "64%",
        dciwmseTarget: "60%",
        workload: "74%",
        workloadTarget: "69%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 209,
        dciwmse: "56%",
        dciwmseTarget: "50%",
        workload: "66%",
        workloadTarget: "61%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 301,
        dciwmse: "65%",
        dciwmseTarget: "61%",
        workload: "75%",
        workloadTarget: "70%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 412,
        dciwmse: "63%",
        dciwmseTarget: "57%",
        workload: "73%",
        workloadTarget: "67%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 523,
        dciwmse: "61%",
        dciwmseTarget: "55%",
        workload: "71%",
        workloadTarget: "66%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 634,
        dciwmse: "59%",
        dciwmseTarget: "53%",
        workload: "69%",
        workloadTarget: "64%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 745,
        dciwmse: "62%",
        dciwmseTarget: "58%",
        workload: "72%",
        workloadTarget: "67%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 856,
        dciwmse: "64%",
        dciwmseTarget: "60%",
        workload: "74%",
        workloadTarget: "69%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 967,
        dciwmse: "58%",
        dciwmseTarget: "52%",
        workload: "68%",
        workloadTarget: "63%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 108,
        dciwmse: "65%",
        dciwmseTarget: "61%",
        workload: "75%",
        workloadTarget: "70%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 219,
        dciwmse: "57%",
        dciwmseTarget: "51%",
        workload: "67%",
        workloadTarget: "62%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 320,
        dciwmse: "60%",
        dciwmseTarget: "55%",
        workload: "70%",
        workloadTarget: "65%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 431,
        dciwmse: "66%",
        dciwmseTarget: "62%",
        workload: "76%",
        workloadTarget: "71%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 454,
        dciwmse: "58%",
        dciwmseTarget: "52%",
        workload: "68%",
        workloadTarget: "63%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 565,
        dciwmse: "61%",
        dciwmseTarget: "56%",
        workload: "71%",
        workloadTarget: "66%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 676,
        dciwmse: "59%",
        dciwmseTarget: "54%",
        workload: "69%",
        workloadTarget: "64%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 787,
        dciwmse: "62%",
        dciwmseTarget: "57%",
        workload: "72%",
        workloadTarget: "67%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 898,
        dciwmse: "64%",
        dciwmseTarget: "60%",
        workload: "74%",
        workloadTarget: "69%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 909,
        dciwmse: "57%",
        dciwmseTarget: "51%",
        workload: "67%",
        workloadTarget: "62%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 110,
        dciwmse: "65%",
        dciwmseTarget: "61%",
        workload: "75%",
        workloadTarget: "70%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 221,
        dciwmse: "60%",
        dciwmseTarget: "55%",
        workload: "70%",
        workloadTarget: "65%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 332,
        dciwmse: "66%",
        dciwmseTarget: "62%",
        workload: "76%",
        workloadTarget: "71%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 443,
        dciwmse: "59%",
        dciwmseTarget: "53%",
        workload: "69%",
        workloadTarget: "64%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 476,
        dciwmse: "63%",
        dciwmseTarget: "57%",
        workload: "73%",
        workloadTarget: "67%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 587,
        dciwmse: "61%",
        dciwmseTarget: "55%",
        workload: "71%",
        workloadTarget: "66%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 698,
        dciwmse: "59%",
        dciwmseTarget: "53%",
        workload: "69%",
        workloadTarget: "64%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 709,
        dciwmse: "62%",
        dciwmseTarget: "58%",
        workload: "72%",
        workloadTarget: "67%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 810,
        dciwmse: "64%",
        dciwmseTarget: "60%",
        workload: "74%",
        workloadTarget: "69%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 921,
        dciwmse: "58%",
        dciwmseTarget: "52%",
        workload: "68%",
        workloadTarget: "63%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 102,
        dciwmse: "65%",
        dciwmseTarget: "61%",
        workload: "75%",
        workloadTarget: "70%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 213,
        dciwmse: "57%",
        dciwmseTarget: "51%",
        workload: "67%",
        workloadTarget: "62%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 324,
        dciwmse: "60%",
        dciwmseTarget: "55%",
        workload: "70%",
        workloadTarget: "65%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 435,
        dciwmse: "66%",
        dciwmseTarget: "62%",
        workload: "76%",
        workloadTarget: "71%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 458,
        dciwmse: "58%",
        dciwmseTarget: "52%",
        workload: "68%",
        workloadTarget: "63%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 569,
        dciwmse: "61%",
        dciwmseTarget: "56%",
        workload: "71%",
        workloadTarget: "66%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 670,
        dciwmse: "59%",
        dciwmseTarget: "54%",
        workload: "69%",
        workloadTarget: "64%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 781,
        dciwmse: "62%",
        dciwmseTarget: "57%",
        workload: "72%",
        workloadTarget: "67%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 892,
        dciwmse: "64%",
        dciwmseTarget: "60%",
        workload: "74%",
        workloadTarget: "69%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 903,
        dciwmse: "57%",
        dciwmseTarget: "51%",
        workload: "67%",
        workloadTarget: "62%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 114,
        dciwmse: "65%",
        dciwmseTarget: "61%",
        workload: "75%",
        workloadTarget: "70%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
      {
        matricule: 225,
        dciwmse: "60%",
        dciwmseTarget: "55%",
        workload: "70%",
        workloadTarget: "65%",
        dailyKaizen: 4,
        dailyKaizenTarget: 3,
      },
      {
        matricule: 336,
        dciwmse: "66%",
        dciwmseTarget: "62%",
        workload: "76%",
        workloadTarget: "71%",
        dailyKaizen: 5,
        dailyKaizenTarget: 4,
      },
      {
        matricule: 447,
        dciwmse: "59%",
        dciwmseTarget: "53%",
        workload: "69%",
        workloadTarget: "64%",
        dailyKaizen: 3,
        dailyKaizenTarget: 2,
      },
    ],
  },
];
