export const USERS = [
  { role: "fa", userName: "fa", token: "xxx.yyy.zzz" },
  { role: "lean", userName: "lean", token: "xxx.yyy.zzz" },
  { role: "cutting", userName: "cutting", token: "xxx.yyy.zzz" },
  { role: "mpc", userName: "mpc", token: "xxx.yyy.zzz" },
  { role: "root", userName: "root", token: "xxx.yyy.zzz" },
];

export const BESTCREW = [
  {
    month: "2024-01",
    data: [
      {
        crew: "k05C",
        efficiency: { act: 94, target: 84 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k01A",
        efficiency: { act: 85, target: 75 },
        abs: { act: "3%", target: "5%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k01B",
        efficiency: { act: 88, target: 78 },
        abs: { act: "2%", target: "4%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k04C",
        efficiency: { act: 90, target: 80 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k05B",
        efficiency: { act: 85, target: 80 },
        abs: { act: "4%", target: "5%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        crew: "k03C",
        efficiency: { act: 90, target: 80 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k02A",
        efficiency: { act: 87, target: 77 },
        abs: { act: "3%", target: "5%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k04B",
        efficiency: { act: 88, target: 78 },
        abs: { act: "2%", target: "4%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k02B",
        efficiency: { act: 89, target: 79 },
        abs: { act: "2%", target: "4%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k02C",
        efficiency: { act: 91, target: 81 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        crew: "k02C",
        efficiency: { act: 91, target: 81 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k03A",
        efficiency: { act: 86, target: 76 },
        abs: { act: "2%", target: "5%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k03B",
        efficiency: { act: 88, target: 78 },
        abs: { act: "2%", target: "4%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k03C",
        efficiency: { act: 90, target: 80 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k05A",
        efficiency: { act: 90, target: 80 },
        abs: { act: "2%", target: "5%" },
        cc: { act: 3, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        crew: "k05A",
        efficiency: { act: 90, target: 80 },
        abs: { act: "2%", target: "5%" },
        cc: { act: 3, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "R04A",
        efficiency: { act: 89, target: 79 },
        abs: { act: "3%", target: "5%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "X04B",
        efficiency: { act: 92, target: 82 },
        abs: { act: "2%", target: "4%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k04C",
        efficiency: { act: 94, target: 84 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k03C",
        efficiency: { act: 90, target: 80 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        crew: "k03A",
        efficiency: { act: 86, target: 76 },
        abs: { act: "2%", target: "5%" },
        cc: { act: 4, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "k05A",
        efficiency: { act: 90, target: 80 },
        abs: { act: "2%", target: "5%" },
        cc: { act: 3, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "R05B",
        efficiency: { act: 85, target: 80 },
        abs: { act: "4%", target: "5%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "B01C",
        efficiency: { act: 88, target: 78 },
        abs: { act: "3%", target: "4%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
      {
        crew: "X03C",
        efficiency: { act: 90, target: 80 },
        abs: { act: "1%", target: "3%" },
        cc: { act: 5, target: 5 },
        dailyKaizen: { act: "100%", target: "100%" },
      },
    ],
  },
];

export const BESTCUTTING = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 6862,
        pmh: "80%",
        setupTime: "70%",
        downTime: "100%",
        oee: "86%",
      },
      {
        matricule: 1234,
        pmh: "85%",
        setupTime: "75%",
        downTime: "100%",
        oee: "88%",
      },
      {
        matricule: 5678,
        pmh: "90%",
        setupTime: "80%",
        downTime: "100%",
        oee: "92%",
      },
      {
        matricule: 4321,
        pmh: "82%",
        setupTime: "72%",
        downTime: "100%",
        oee: "87%",
      },
      {
        matricule: 8765,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        oee: "89%",
      },
      {
        matricule: 3456,
        pmh: "81%",
        setupTime: "71%",
        downTime: "100%",
        oee: "86%",
      },
      {
        matricule: 7890,
        pmh: "87%",
        setupTime: "77%",
        downTime: "100%",
        oee: "90%",
      },
      {
        matricule: 4567,
        pmh: "83%",
        setupTime: "73%",
        downTime: "100%",
        oee: "88%",
      },
      {
        matricule: 8901,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        oee: "89%",
      },
      {
        matricule: 5670,
        pmh: "89%",
        setupTime: "79%",
        downTime: "100%",
        oee: "91%",
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 2345,
        pmh: "82%",
        setupTime: "72%",
        downTime: "100%",
        oee: "87%",
      },
      {
        matricule: 6789,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        oee: "89%",
      },
      {
        matricule: 3452,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        oee: "88%",
      },
      {
        matricule: 7893,
        pmh: "81%",
        setupTime: "71%",
        downTime: "100%",
        oee: "86%",
      },
      {
        matricule: 4568,
        pmh: "87%",
        setupTime: "77%",
        downTime: "100%",
        oee: "90%",
      },
      {
        matricule: 8902,
        pmh: "83%",
        setupTime: "73%",
        downTime: "100%",
        oee: "88%",
      },
      {
        matricule: 5671,
        pmh: "89%",
        setupTime: "79%",
        downTime: "100%",
        oee: "91%",
      },
      {
        matricule: 6780,
        pmh: "85%",
        setupTime: "75%",
        downTime: "100%",
        oee: "89%",
      },
      {
        matricule: 7891,
        pmh: "88%",
        setupTime: "78%",
        downTime: "100%",
        oee: "90%",
      },
      {
        matricule: 8903,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        oee: "89%",
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 3456,
        pmh: "83%",
        setupTime: "73%",
        downTime: "100%",
        oee: "88%",
      },
      {
        matricule: 7890,
        pmh: "87%",
        setupTime: "77%",
        downTime: "100%",
        oee: "90%",
      },
      {
        matricule: 4567,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        oee: "88%",
      },
      {
        matricule: 8901,
        pmh: "85%",
        setupTime: "75%",
        downTime: "100%",
        oee: "89%",
      },
      {
        matricule: 5670,
        pmh: "81%",
        setupTime: "71%",
        downTime: "100%",
        oee: "86%",
      },
      {
        matricule: 6780,
        pmh: "89%",
        setupTime: "79%",
        downTime: "100%",
        oee: "91%",
      },
      {
        matricule: 7891,
        pmh: "88%",
        setupTime: "78%",
        downTime: "100%",
        oee: "90%",
      },
      {
        matricule: 8902,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        oee: "89%",
      },
      {
        matricule: 5671,
        pmh: "82%",
        setupTime: "72%",
        downTime: "100%",
        oee: "87%",
      },
      {
        matricule: 6781,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        oee: "88%",
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 4567,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        oee: "89%",
      },
      {
        matricule: 8901,
        pmh: "82%",
        setupTime: "72%",
        downTime: "100%",
        oee: "87%",
      },
      {
        matricule: 5670,
        pmh: "83%",
        setupTime: "73%",
        downTime: "100%",
        oee: "88%",
      },
      {
        matricule: 6780,
        pmh: "89%",
        setupTime: "79%",
        downTime: "100%",
        oee: "91%",
      },
      {
        matricule: 7891,
        pmh: "88%",
        setupTime: "78%",
        downTime: "100%",
        oee: "90%",
      },
      {
        matricule: 8902,
        pmh: "85%",
        setupTime: "75%",
        downTime: "100%",
        oee: "89%",
      },
      {
        matricule: 5671,
        pmh: "87%",
        setupTime: "77%",
        downTime: "100%",
        oee: "90%",
      },
      {
        matricule: 6781,
        pmh: "81%",
        setupTime: "71%",
        downTime: "100%",
        oee: "86%",
      },
      {
        matricule: 7892,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        oee: "88%",
      },
      {
        matricule: 8903,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        oee: "89%",
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 5670,
        pmh: "80%",
        setupTime: "70%",
        downTime: "100%",
        oee: "86%",
      },
      {
        matricule: 6780,
        pmh: "85%",
        setupTime: "75%",
        downTime: "100%",
        oee: "88%",
      },
      {
        matricule: 7890,
        pmh: "90%",
        setupTime: "80%",
        downTime: "100%",
        oee: "92%",
      },
      {
        matricule: 8900,
        pmh: "82%",
        setupTime: "72%",
        downTime: "100%",
        oee: "87%",
      },
      {
        matricule: 1234,
        pmh: "84%",
        setupTime: "74%",
        downTime: "100%",
        oee: "89%",
      },
      {
        matricule: 2345,
        pmh: "81%",
        setupTime: "71%",
        downTime: "100%",
        oee: "86%",
      },
      {
        matricule: 3456,
        pmh: "87%",
        setupTime: "77%",
        downTime: "100%",
        oee: "90%",
      },
      {
        matricule: 4567,
        pmh: "83%",
        setupTime: "73%",
        downTime: "100%",
        oee: "88%",
      },
      {
        matricule: 5678,
        pmh: "86%",
        setupTime: "76%",
        downTime: "100%",
        oee: "89%",
      },
      {
        matricule: 6789,
        pmh: "89%",
        setupTime: "79%",
        downTime: "100%",
        oee: "91%",
      },
    ],
  },
];

export const BESTLPOP = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 6268,
        pmh: "86%",
      },
      {
        matricule: 1234,
        pmh: "85%",
      },
      {
        matricule: 5678,
        pmh: "90%",
      },
      {
        matricule: 4321,
        pmh: "82%",
      },
      {
        matricule: 8765,
        pmh: "84%",
      },
      {
        matricule: 3456,
        pmh: "81%",
      },
      {
        matricule: 7890,
        pmh: "87%",
      },
      {
        matricule: 4567,
        pmh: "83%",
      },
      {
        matricule: 8901,
        pmh: "86%",
      },
      {
        matricule: 5670,
        pmh: "89%",
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 2345,
        pmh: "82%",
      },
      {
        matricule: 6789,
        pmh: "86%",
      },
      {
        matricule: 3452,
        pmh: "84%",
      },
      {
        matricule: 7893,
        pmh: "81%",
      },
      {
        matricule: 4568,
        pmh: "87%",
      },
      {
        matricule: 8902,
        pmh: "83%",
      },
      {
        matricule: 5671,
        pmh: "89%",
      },
      {
        matricule: 6780,
        pmh: "85%",
      },
      {
        matricule: 7891,
        pmh: "88%",
      },
      {
        matricule: 8903,
        pmh: "86%",
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 3456,
        pmh: "83%",
      },
      {
        matricule: 7890,
        pmh: "87%",
      },
      {
        matricule: 4567,
        pmh: "84%",
      },
      {
        matricule: 8901,
        pmh: "85%",
      },
      {
        matricule: 5670,
        pmh: "81%",
      },
      {
        matricule: 6780,
        pmh: "89%",
      },
      {
        matricule: 7891,
        pmh: "88%",
      },
      {
        matricule: 8902,
        pmh: "86%",
      },
      {
        matricule: 5671,
        pmh: "82%",
      },
      {
        matricule: 6781,
        pmh: "84%",
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 4567,
        pmh: "86%",
      },
      {
        matricule: 8901,
        pmh: "82%",
      },
      {
        matricule: 5670,
        pmh: "83%",
      },
      {
        matricule: 6780,
        pmh: "89%",
      },
      {
        matricule: 7891,
        pmh: "88%",
      },
      {
        matricule: 8902,
        pmh: "85%",
      },
      {
        matricule: 5671,
        pmh: "87%",
      },
      {
        matricule: 6781,
        pmh: "81%",
      },
      {
        matricule: 7892,
        pmh: "84%",
      },
      {
        matricule: 8903,
        pmh: "86%",
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 5670,
        pmh: "80%",
      },
      {
        matricule: 6780,
        pmh: "85%",
      },
      {
        matricule: 7890,
        pmh: "90%",
      },
      {
        matricule: 8900,
        pmh: "82%",
      },
      {
        matricule: 1234,
        pmh: "84%",
      },
      {
        matricule: 2345,
        pmh: "81%",
      },
      {
        matricule: 3456,
        pmh: "87%",
      },
      {
        matricule: 4567,
        pmh: "83%",
      },
      {
        matricule: 5678,
        pmh: "86%",
      },
      {
        matricule: 6789,
        pmh: "89%",
      },
    ],
  },
];

export const QUALITYHERO = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 2635,
        detection: 4,
        occurrence: 2,
        security: 3,
      },
      {
        matricule: 1234,
        detection: 3,
        occurrence: 1,
        security: 4,
      },
      {
        matricule: 5678,
        detection: 2,
        occurrence: 4,
        security: 5,
      },
      {
        matricule: 4321,
        detection: 5,
        occurrence: 3,
        security: 1,
      },
      {
        matricule: 8765,
        detection: 1,
        occurrence: 5,
        security: 2,
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 3456,
        detection: 3,
        occurrence: 2,
        security: 5,
      },
      {
        matricule: 7890,
        detection: 4,
        occurrence: 1,
        security: 3,
      },
      {
        matricule: 4567,
        detection: 2,
        occurrence: 3,
        security: 4,
      },
      {
        matricule: 8901,
        detection: 5,
        occurrence: 4,
        security: 1,
      },
      {
        matricule: 5670,
        detection: 1,
        occurrence: 5,
        security: 2,
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 6780,
        detection: 2,
        occurrence: 1,
        security: 4,
      },
      {
        matricule: 7891,
        detection: 3,
        occurrence: 5,
        security: 2,
      },
      {
        matricule: 8902,
        detection: 4,
        occurrence: 2,
        security: 3,
      },
      {
        matricule: 5671,
        detection: 1,
        occurrence: 4,
        security: 5,
      },
      {
        matricule: 6781,
        detection: 5,
        occurrence: 3,
        security: 1,
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 7892,
        detection: 4,
        occurrence: 5,
        security: 2,
      },
      {
        matricule: 8903,
        detection: 3,
        occurrence: 1,
        security: 4,
      },
      {
        matricule: 5672,
        detection: 2,
        occurrence: 3,
        security: 5,
      },
      {
        matricule: 6782,
        detection: 1,
        occurrence: 4,
        security: 3,
      },
      {
        matricule: 7893,
        detection: 5,
        occurrence: 2,
        security: 1,
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 8904,
        detection: 3,
        occurrence: 4,
        security: 2,
      },
      {
        matricule: 5673,
        detection: 4,
        occurrence: 1,
        security: 5,
      },
      {
        matricule: 6783,
        detection: 2,
        occurrence: 5,
        security: 3,
      },
      {
        matricule: 7894,
        detection: 5,
        occurrence: 2,
        security: 1,
      },
      {
        matricule: 8905,
        detection: 1,
        occurrence: 3,
        security: 4,
      },
    ],
  },
];

export const SAFETYHERO = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 3456,
        detection: 2,
        occurrence: 3,
        security: 4,
      },
      {
        matricule: 7890,
        detection: 4,
        occurrence: 1,
        security: 5,
      },
      {
        matricule: 1235,
        detection: 3,
        occurrence: 2,
        security: 1,
      },
      {
        matricule: 6789,
        detection: 5,
        occurrence: 4,
        security: 3,
      },
      {
        matricule: 4568,
        detection: 1,
        occurrence: 5,
        security: 2,
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 2345,
        detection: 4,
        occurrence: 1,
        security: 3,
      },
      {
        matricule: 6780,
        detection: 3,
        occurrence: 5,
        security: 2,
      },
      {
        matricule: 5671,
        detection: 1,
        occurrence: 4,
        security: 5,
      },
      {
        matricule: 8902,
        detection: 2,
        occurrence: 3,
        security: 1,
      },
      {
        matricule: 7891,
        detection: 5,
        occurrence: 2,
        security: 4,
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 5670,
        detection: 3,
        occurrence: 4,
        security: 2,
      },
      {
        matricule: 6781,
        detection: 4,
        occurrence: 1,
        security: 5,
      },
      {
        matricule: 8903,
        detection: 2,
        occurrence: 5,
        security: 3,
      },
      {
        matricule: 7892,
        detection: 1,
        occurrence: 3,
        security: 4,
      },
      {
        matricule: 5672,
        detection: 5,
        occurrence: 2,
        security: 1,
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 6782,
        detection: 3,
        occurrence: 4,
        security: 5,
      },
      {
        matricule: 8904,
        detection: 1,
        occurrence: 5,
        security: 2,
      },
      {
        matricule: 7893,
        detection: 4,
        occurrence: 2,
        security: 1,
      },
      {
        matricule: 5673,
        detection: 5,
        occurrence: 3,
        security: 4,
      },
      {
        matricule: 6783,
        detection: 2,
        occurrence: 1,
        security: 3,
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 8905,
        detection: 5,
        occurrence: 4,
        security: 3,
      },
      {
        matricule: 7894,
        detection: 1,
        occurrence: 3,
        security: 5,
      },
      {
        matricule: 5674,
        detection: 4,
        occurrence: 2,
        security: 1,
      },
      {
        matricule: 6784,
        detection: 2,
        occurrence: 5,
        security: 4,
      },
      {
        matricule: 8906,
        detection: 3,
        occurrence: 1,
        security: 2,
      },
    ],
  },
];

export const LEANHERO = [
  {
    month: "2024-01",
    data: [
      {
        matricule: 3456,
        detection: 2,
        occurrence: 3,
        security: 4,
      },
      {
        matricule: 7890,
        detection: 4,
        occurrence: 1,
        security: 5,
      },
      {
        matricule: 1235,
        detection: 3,
        occurrence: 2,
        security: 1,
      },
      {
        matricule: 6789,
        detection: 5,
        occurrence: 4,
        security: 3,
      },
      {
        matricule: 4568,
        detection: 1,
        occurrence: 5,
        security: 2,
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        matricule: 2345,
        detection: 4,
        occurrence: 1,
        security: 3,
      },
      {
        matricule: 6780,
        detection: 3,
        occurrence: 5,
        security: 2,
      },
      {
        matricule: 5671,
        detection: 1,
        occurrence: 4,
        security: 5,
      },
      {
        matricule: 8902,
        detection: 2,
        occurrence: 3,
        security: 1,
      },
      {
        matricule: 7891,
        detection: 5,
        occurrence: 2,
        security: 4,
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        matricule: 5670,
        detection: 3,
        occurrence: 4,
        security: 2,
      },
      {
        matricule: 6781,
        detection: 4,
        occurrence: 1,
        security: 5,
      },
      {
        matricule: 8903,
        detection: 2,
        occurrence: 5,
        security: 3,
      },
      {
        matricule: 7892,
        detection: 1,
        occurrence: 3,
        security: 4,
      },
      {
        matricule: 5672,
        detection: 5,
        occurrence: 2,
        security: 1,
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        matricule: 6782,
        detection: 3,
        occurrence: 4,
        security: 5,
      },
      {
        matricule: 8904,
        detection: 1,
        occurrence: 5,
        security: 2,
      },
      {
        matricule: 7893,
        detection: 4,
        occurrence: 2,
        security: 1,
      },
      {
        matricule: 5673,
        detection: 5,
        occurrence: 3,
        security: 4,
      },
      {
        matricule: 6783,
        detection: 2,
        occurrence: 1,
        security: 3,
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        matricule: 8905,
        detection: 5,
        occurrence: 4,
        security: 3,
      },
      {
        matricule: 7894,
        detection: 1,
        occurrence: 3,
        security: 5,
      },
      {
        matricule: 5674,
        detection: 4,
        occurrence: 2,
        security: 1,
      },
      {
        matricule: 6784,
        detection: 2,
        occurrence: 5,
        security: 4,
      },
      {
        matricule: 8906,
        detection: 3,
        occurrence: 1,
        security: 2,
      },
    ],
  },
];

export const PROJECTCI = [
  {
    month: "2024-01",
    data: [
      {
        projectName: "Customer Service",
        leader: "Wafaa",
        teamMembers: ["Ibrahim", "Sara"],
        saving: 490,
        approach: "Improving customer interaction methods",
      },
      {
        projectName: "Automation",
        leader: "Fatima",
        teamMembers: ["Khalid", "Sami"],
        saving: 500,
        approach: "Streamlining workflows with AI tools",
      },
      {
        projectName: "Optimization",
        leader: "Mehdi",
        teamMembers: ["Laila", "Nour"],
        saving: 600,
        approach: "Enhancing data analysis methods",
      },
      {
        projectName: "Digitization",
        leader: "Rachid",
        teamMembers: ["Yasmine", "Hamza"],
        saving: 450,
        approach: "Converting manual processes to digital",
      },
      {
        projectName: "Sustainability",
        leader: "Sara",
        teamMembers: ["Amine", "Sofia"],
        saving: 550,
        approach: "Implementing eco-friendly practices",
      },
      {
        projectName: "Innovation",
        leader: "Hassan",
        teamMembers: ["Omar", "Layla"],
        saving: 620,
        approach: "Developing new product features",
      },
      {
        projectName: "Expansion",
        leader: "Khadija",
        teamMembers: ["Mohammed", "Nada"],
        saving: 480,
        approach: "Exploring new market opportunities",
      },
      {
        projectName: "Integration",
        leader: "Youssef",
        teamMembers: ["Zineb", "Salma"],
        saving: 700,
        approach: "Combining systems for efficiency",
      },
      {
        projectName: "Training",
        leader: "Amina",
        teamMembers: ["Ali", "Nadia"],
        saving: 510,
        approach: "Enhancing skills through workshops",
      },
      {
        projectName: "Research",
        leader: "Karim",
        teamMembers: ["Mounir", "Rania"],
        saving: 530,
        approach: "Conducting in-depth market analysis",
      },
    ],
  },
  {
    month: "2024-02",
    data: [
      {
        projectName: "Security",
        leader: "Othman",
        teamMembers: ["Hiba", "Samir"],
        saving: 470,
        approach: "Implementing advanced security protocols",
      },
      {
        projectName: "Customer Service",
        leader: "Wafaa",
        teamMembers: ["Ibrahim", "Sara"],
        saving: 490,
        approach: "Improving customer interaction methods",
      },
      {
        projectName: "Compliance",
        leader: "Ismail",
        teamMembers: ["Farah", "Younes"],
        saving: 610,
        approach: "Ensuring adherence to regulations",
      },
      {
        projectName: "Collaboration",
        leader: "Samira",
        teamMembers: ["Meryem", "Yassine"],
        saving: 560,
        approach: "Enhancing team collaboration tools",
      },
      {
        projectName: "Sustainability",
        leader: "Sara",
        teamMembers: ["Amine", "Sofia"],
        saving: 550,
        approach: "Implementing eco-friendly practices",
      },
      {
        projectName: "Expansion",
        leader: "Khadija",
        teamMembers: ["Mohammed", "Nada"],
        saving: 480,
        approach: "Exploring new market opportunities",
      },
      {
        projectName: "Integration",
        leader: "Youssef",
        teamMembers: ["Zineb", "Salma"],
        saving: 700,
        approach: "Combining systems for efficiency",
      },
      {
        projectName: "Training",
        leader: "Amina",
        teamMembers: ["Ali", "Nadia"],
        saving: 510,
        approach: "Enhancing skills through workshops",
      },
      {
        projectName: "Research",
        leader: "Karim",
        teamMembers: ["Mounir", "Rania"],
        saving: 530,
        approach: "Conducting in-depth market analysis",
      },
      {
        projectName: "Innovation",
        leader: "Hassan",
        teamMembers: ["Omar", "Layla"],
        saving: 620,
        approach: "Developing new product features",
      },
    ],
  },
  {
    month: "2024-03",
    data: [
      {
        projectName: "Automation",
        leader: "Fatima",
        teamMembers: ["Khalid", "Sami"],
        saving: 500,
        approach: "Streamlining workflows with AI tools",
      },
      {
        projectName: "Optimization",
        leader: "Mehdi",
        teamMembers: ["Laila", "Nour"],
        saving: 600,
        approach: "Enhancing data analysis methods",
      },
      {
        projectName: "Digitization",
        leader: "Rachid",
        teamMembers: ["Yasmine", "Hamza"],
        saving: 450,
        approach: "Converting manual processes to digital",
      },
      {
        projectName: "Security",
        leader: "Othman",
        teamMembers: ["Hiba", "Samir"],
        saving: 470,
        approach: "Implementing advanced security protocols",
      },
      {
        projectName: "Customer Service",
        leader: "Wafaa",
        teamMembers: ["Ibrahim", "Sara"],
        saving: 490,
        approach: "Improving customer interaction methods",
      },
      {
        projectName: "Compliance",
        leader: "Ismail",
        teamMembers: ["Farah", "Younes"],
        saving: 610,
        approach: "Ensuring adherence to regulations",
      },
      {
        projectName: "Collaboration",
        leader: "Samira",
        teamMembers: ["Meryem", "Yassine"],
        saving: 560,
        approach: "Enhancing team collaboration tools",
      },
      {
        projectName: "Innovation",
        leader: "Hassan",
        teamMembers: ["Omar", "Layla"],
        saving: 620,
        approach: "Developing new product features",
      },
      {
        projectName: "Expansion",
        leader: "Khadija",
        teamMembers: ["Mohammed", "Nada"],
        saving: 480,
        approach: "Exploring new market opportunities",
      },
      {
        projectName: "Integration",
        leader: "Youssef",
        teamMembers: ["Zineb", "Salma"],
        saving: 700,
        approach: "Combining systems for efficiency",
      },
    ],
  },
  {
    month: "2024-04",
    data: [
      {
        projectName: "Training",
        leader: "Amina",
        teamMembers: ["Ali", "Nadia"],
        saving: 510,
        approach: "Enhancing skills through workshops",
      },
      {
        projectName: "Research",
        leader: "Karim",
        teamMembers: ["Mounir", "Rania"],
        saving: 530,
        approach: "Conducting in-depth market analysis",
      },
      {
        projectName: "Optimization",
        leader: "Mehdi",
        teamMembers: ["Laila", "Nour"],
        saving: 600,
        approach: "Enhancing data analysis methods",
      },
      {
        projectName: "Digitization",
        leader: "Rachid",
        teamMembers: ["Yasmine", "Hamza"],
        saving: 450,
        approach: "Converting manual processes to digital",
      },
      {
        projectName: "Sustainability",
        leader: "Sara",
        teamMembers: ["Amine", "Sofia"],
        saving: 550,
        approach: "Implementing eco-friendly practices",
      },
      {
        projectName: "Innovation",
        leader: "Hassan",
        teamMembers: ["Omar", "Layla"],
        saving: 620,
        approach: "Developing new product features",
      },
      {
        projectName: "Expansion",
        leader: "Khadija",
        teamMembers: ["Mohammed", "Nada"],
        saving: 480,
        approach: "Exploring new market opportunities",
      },
      {
        projectName: "Integration",
        leader: "Youssef",
        teamMembers: ["Zineb", "Salma"],
        saving: 700,
        approach: "Combining systems for efficiency",
      },
      {
        projectName: "Automation",
        leader: "Fatima",
        teamMembers: ["Khalid", "Sami"],
        saving: 500,
        approach: "Streamlining workflows with AI tools",
      },
      {
        projectName: "Collaboration",
        leader: "Samira",
        teamMembers: ["Meryem", "Yassine"],
        saving: 560,
        approach: "Enhancing team collaboration tools",
      },
    ],
  },
  {
    month: "2024-05",
    data: [
      {
        projectName: "Recognition",
        leader: "Ouassil",
        teamMembers: ["Anass", "Yazid"],
        saving: 400,
        approach:
          "Development of an app to facilitate and improve the process of the recognition ceremony in the company",
      },

      {
        projectName: "Compliance",
        leader: "Ismail",
        teamMembers: ["Farah", "Younes"],
        saving: 610,
        approach: "Ensuring adherence to regulations",
      },
      {
        projectName: "Collaboration",
        leader: "Samira",
        teamMembers: ["Meryem", "Yassine"],
        saving: 560,
        approach: "Enhancing team collaboration tools",
      },
      {
        projectName: "Training",
        leader: "Amina",
        teamMembers: ["Ali", "Nadia"],
        saving: 510,
        approach: "Enhancing skills through workshops",
      },
      {
        projectName: "Research",
        leader: "Karim",
        teamMembers: ["Mounir", "Rania"],
        saving: 530,
        approach: "Conducting in-depth market analysis",
      },
      {
        projectName: "Sustainability",
        leader: "Sara",
        teamMembers: ["Amine", "Sofia"],
        saving: 550,
        approach: "Implementing eco-friendly practices",
      },
      {
        projectName: "Optimization",
        leader: "Mehdi",
        teamMembers: ["Laila", "Nour"],
        saving: 600,
        approach: "Enhancing data analysis methods",
      },
      {
        projectName: "Digitalization",
        leader: "Rachid",
        teamMembers: ["Yasmine", "Hamza"],
        saving: 450,
        approach: "Converting manual processes to digital",
      },
      {
        projectName: "Innovation",
        leader: "Hassan",
        teamMembers: ["Omar", "Layla"],
        saving: 620,
        approach: "Developing new product features",
      },
      {
        projectName: "Expansion",
        leader: "Khadija",
        teamMembers: ["Mohammed", "Nada"],
        saving: 480,
        approach: "Exploring new market opportunities",
      },
    ],
  },
];
